@startuml
interface BeanDefiniton
abstract AbstractBeanDefiniton

BeanDefiniton <|.. AbstractBeanDefiniton

AbstractBeanDefiniton <|-- RootBeanDefiniton
AbstractBeanDefiniton <|-- GenericBeanDefiniton
AbstractBeanDefiniton <|-- ChildBeanDefiniton



@enduml